# this file contains options for generating Github pages and is
# likely incompatabible with local environments in minor ways
# local builds should use:
# jekyll build --config _local.yml
theme: jekyll-theme-modernist
